// PLCdesk -> EPLAN Electric P8: import of PLC data (AutomationML AR APC) and optional "Generate PLC schematic".
//
// EPLAN script (C#, runs in EPLAN's own scripting engine - no EPLAN API licence needed).
// Run: File > Extras > Scripts > Run... (DE: Datei > Extras > Skripte > Ausfuehren), choose this file,
// then pick the *_AR_APC.aml exported by PLCdesk. The target project must be open and selected.
//
// Actions used (syntax per eplan.help):
//   selectionset /TYPE:PROJECT             https://www.eplan.help/en-us/Infoportal/Content/api/2027/selectionset.html
//   plcservice /TYPE:BUSDATAIMPORT ...     https://www.eplan.help/en-us/Infoportal/Content/api/2027/plcservice.html
//   plcservice /TYPE:GENERATEPLCSCHEMATIC  (same page; CONFIGFILE = saved "Generate PLC schematic" settings)
//   scripts calling actions               https://www.eplan.help/en-US/infoportal/content/api/2025/SimpleScriptWithParameters.html
//
// STATUS: NOT VERIFIED in EPLAN (no EPLAN licence available to PLCdesk). Check the first import manually.
// Pages are only drawn for parts that have a macro in the customer's master data (found via the order
// number = "PLC type designation"); generating schematics may require the EPLAN "PLC & Bus Extension".
//
// Generated by PLCdesk - identical to apps/eplan/PLCdesk_ImportAML.cs in the PLCdesk repository.
using System;
using System.IO;
using System.Text.RegularExpressions;
using System.Windows.Forms;
using Eplan.EplApi.ApplicationFramework;
using Eplan.EplApi.Scripting;

public class PLCdesk_ImportAML
{
    // ---------------------------------------------------------------- settings (edit if needed)
    // Converter: "" = by file content (Siemens SIMATIC -> PlcDcExchangerSiemensTIA19AML, otherwise
    // PlcDcAMLExchangerGeneral = "Eplan Electric P8 AML-format"). Other IDs: PlcDcExchangerSiemensTIA20AML,
    // PlcDcExchangerSiemensTIA21AML, PlcDcExchangerBeckhoffTC3AML, PlcDcExchangerRockwellArchitectAML ...
    const string ConverterId = "";
    // Language of texts without a language tag: "" = from the file (PLCdesk writes <!-- PLCdesk language=xx_XX -->).
    const string Language = "";
    // Matching: "0" = by internal object IDs (PLCdesk GUIDs - a repeated import updates objects),
    // "1" = by identifying names, "2" = do not match (always create new functions).
    const string ImportMatch = "0";
    // Saved settings of "Generate PLC schematic" (customer's own configuration file); "" = skip generation.
    const string SchematicConfigFile = "";

    [Start]
    public void Run()
    {
        string project = CurrentProject();
        if (project == "")
        {
            MessageBox.Show("Open and select the target EPLAN project first.", "PLCdesk");
            return;
        }
        OpenFileDialog dlg = new OpenFileDialog();
        dlg.Title = "PLCdesk - AutomationML AR APC (*.aml)";
        dlg.Filter = "AutomationML (*.aml)|*.aml|All files (*.*)|*.*";
        if (dlg.ShowDialog() != DialogResult.OK) return;
        string aml = dlg.FileName;
        string text = File.ReadAllText(aml);
        string converter = ConverterId != "" ? ConverterId : DetectConverter(text);
        string language = Language != "" ? Language : DetectLanguage(text);

        ActionCallingContext imp = new ActionCallingContext();
        imp.AddParameter("TYPE", "BUSDATAIMPORT");
        imp.AddParameter("PROJECTNAME", project);
        imp.AddParameter("SOURCEFILE", aml);
        imp.AddParameter("LANGUAGE", language);
        imp.AddParameter("CONVERTERID", converter);
        imp.AddParameter("IMPORTMATCH", ImportMatch);
        bool ok = new CommandLineInterpreter().Execute("plcservice", imp);
        if (!ok)
        {
            MessageBox.Show("PLC data import failed (converter " + converter + ").\nTry the dialog Project data > PLC > Import PLC data, or another converter.", "PLCdesk");
            return;
        }
        if (SchematicConfigFile == "")
        {
            MessageBox.Show("PLC data imported (" + converter + ", " + language + ").\nNext: Generate PLC schematic with your settings, or set SchematicConfigFile in this script.", "PLCdesk");
            return;
        }
        ActionCallingContext gen = new ActionCallingContext();
        gen.AddParameter("TYPE", "GENERATEPLCSCHEMATIC");
        gen.AddParameter("PROJECTNAME", project);
        gen.AddParameter("CONFIGFILE", SchematicConfigFile);
        ok = new CommandLineInterpreter().Execute("plcservice", gen);
        MessageBox.Show(ok ? "PLC data imported and schematic generated - check the new pages." : "PLC data imported, schematic generation failed (licence, macros or configuration file).", "PLCdesk");
    }

    static string CurrentProject()
    {
        ActionCallingContext ctx = new ActionCallingContext();
        ctx.AddParameter("TYPE", "PROJECT");
        new CommandLineInterpreter().Execute("selectionset", ctx);
        string project = "";
        ctx.GetParameter("PROJECT", ref project);
        return project ?? "";
    }

    static string DetectConverter(string text)
    {
        bool siemens = text.Contains("System:Device.S71200") || text.Contains("System:Device.S71500")
            || text.Contains("System:Device.ET200SP") || text.Contains("OrderNumber:6ES7");
        return siemens ? "PlcDcExchangerSiemensTIA19AML" : "PlcDcAMLExchangerGeneral";
    }

    static string DetectLanguage(string text)
    {
        Match m = Regex.Match(text, "<!-- PLCdesk language=([a-z]{2}_[A-Z]{2}) -->");
        return m.Success ? m.Groups[1].Value : "en_US";
    }
}
